### ISSUE TITLE
come back to life those changes and share

### ISSUE THREAD

**Issue by albfan** [m45t3r/terminator-gtk3-py3#1]
I use terminator or regular basis and would like to make some improvements and add a couple of features.

I found annoying to work on bazaar, so I exported to git too. Once do that, is hard to keep up-to-date with bazaar progress.

FYI this is the way I do (seems to work). 

https://github.com/albfan/terminator/blob/master/GIT-HACKING.md

If I can I would like to "not reinvent the weel" so I'm asking all terminator hackers (there's a lot) to rebase it's improvements and cooperate on a main repo. First steps is to share a common import (everyone with it's commits upon HEAD at the time they was done) and see what is fixed and what would be cool to do.

**Comment by thiagokokada** [comment]
It is unlikely that I ever work with vanilla terminator since I have quite a different vision of how a terminal in Python should be written. My idea is to simplify the code, remove features that I don't normally use and after that, work to make a extensive terminal using Python itself.

What it means? I would like to have a small code base with all configuration made using Python code, so to configure some behavior you would actually import and make some changes in the source itself. Yeah, this is crazy, this is why I didn't make it yet.

Anyway, if someday I resolve that my idea is too crazy and I decide to contribute to terminator itself, I may contribute it to the main repository. This was kind of some failed experiment (and the fact that nowadays I prefer to simple use tmux does not help). However, I want to play with this code someday again.

**Comment by albfan** [comment]
Let me know if you make some progress!
